// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/cart': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cart/index.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cart/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cart/index.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cart/index.put').default>>>>
    }
    '/api/cookies': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cookies').default>>>>
    }
    '/api/github': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/github/index.get').default>>>>
    }
    '/api/posts/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/[id]/index.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/[id]/index.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/[id]/index.put').default>>>>
    }
    '/api/posts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/index.post').default>>>>
    }
    '/api/sample': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sample').default>>>>
    }
    '/api/submit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/submit.post').default>>>>
    }
    '/api/test': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test.post').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.get').default>>>>
    }
    '/sample': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/sample').default>>>>
    }
    '/users/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/users/[id]').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}